### ISSUE TITLE
Support a map for `networks` as well as `string[]`

### ISSUE THREAD

**Issue by TylerRick** [micahhausler/container-tx#5]
Documented here: https://docs.docker.com/compose/compose-file/#aliases

## Example:
```
⟫ cat docker-compose-network-map.yml
version: '2'
services:
  postgres:
    image: mdillon/postgis:9.5
    networks:
      default:
        aliases:
          - db
```

**Current behavior:**
```
⟫ ./container-tx < docker-compose-network-map.yml
Error ingesting file: yaml: unmarshal errors:
  line 6: cannot unmarshal !!map into []string 
```

**Expected:**

I'm guessing something like this (not 100% sure yet):
```
⟫ ./container-tx < docker-compose-network-map.yml
docker network create projectname_default

######## postgres ########
docker run \
    --name postgres \
    --network projectname_default \
    --network-alias db \
    mdillon/postgis:9.5
```
